{{- $image := printf "%s%s" .Values.registry .Values.archiver.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-archiver
spec:
  replicas: {{ .Values.archiver.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-archiver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-archiver
    spec:
      tolerations:
      - key: dorch
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        dorch: "true"
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
{{- end }}
      volumes:
      - name: data
        hostPath:
          path: /data
          type: DirectoryOrCreate
      initContainers:
      - name: init
        image: {{ .Values.archiver.init.image }}
        imagePullPolicy: {{ .Values.archiver.init.imagePullPolicy }}
        command:
        - /download-iwads.sh
        env:
{{ include "dorch.redis-env" . | indent 8 }}
        - name: IWADS_DIR
          value: /data/iwads
        - name: DORCH_TMP_PATH
          value: /data/tmp
        - name: IWAD_BUCKET
          value: {{ .Values.archiver.init.s3.bucket }}
        - name: AWS_ACCESS_KEY_ID
{{ toYaml .Values.archiver.init.s3.accessKeyId | indent 10 }}
        - name: AWS_SECRET_ACCESS_KEY
{{ toYaml .Values.archiver.init.s3.secretAccessKey | indent 10 }}
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.archiver.init.s3.region }}
        - name: AWS_ENDPOINT_URL
          value: {{ .Values.archiver.init.s3.endpoint }}
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
        - name: AWS_S3_FORCE_PATH_STYLE
          value: "true"
{{- if .Values.archiver.init.resources }}
        resources:
{{ toYaml .Values.archiver.init.resources | indent 10 }}
{{- end }}
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: archiver
        imagePullPolicy: {{ .Values.archiver.imagePullPolicy }}
        image: {{ $image }}
{{- if .Values.archiver.resources }}
        resources:
{{ toYaml .Values.archiver.resources | indent 10 }}
{{- end }}
        command:
          - python
          - /app/meta-worker.py
{{- if .Values.prometheus.enabled }}
        ports:
        - containerPort: 2112
          protocol: TCP
          name: metrics
{{- end }}
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/ready
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: DORCH_POST_TO_WADINFO
          value: "1"
        - name: WADINFO_BASE_URL
          value: "http://{{ .Release.Name }}-wadinfo"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DORCH_READY_FILE
          value: /etc/ready
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: spaces-cred
              key: secret_access_key
        - name: IWADS_DIR
          value: /data/iwads
        - name: SERVICE_NAME
          value: archiver
        - name: RUST_LOG
          value: info,aws_smithy_runtime=debug,aws_smithy_http_tower=debug,hyper=info
        - name: LOG_LEVEL
          value: {{ .Values.archiver.logLevel }}
        - name: DOOMWADDIR
          value: /data/iwads
{{- if .Values.prometheus.enabled }}
        - name: DORCH_METRICS_ENABLED
          value: "true"
        - name: DORCH_METRICS_PORT
          value: "2112"
{{- end }}
{{- if .Values.nats.user }}
        - name: NATS_USER
{{ tpl (toYaml .Values.nats.user) . | indent 10 }}
{{- end }}
{{- if .Values.nats.password }}
        - name: NATS_PASSWORD
{{ tpl (toYaml .Values.nats.password) . | indent 10 }}
{{- end }}
{{ include "dorch.metrics-env" . | indent 8 }}
{{ include "dorch.nats-env" . | indent 8 }}
        volumeMounts:
        - name: data
          mountPath: /data
---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-archiver
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-archiver
  podMetricsEndpoints:
  - port: metrics
{{- end }}