apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-browser
spec:
  replicas: {{ .Values.browser.replicas}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-browser
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-browser
    spec:
      restartPolicy: Always
      containers:
      - name: browser
        imagePullPolicy: {{ .Values.browser.imagePullPolicy }}
        image: {{ .Values.browser.image }}
    {{- if .Values.browser.resources }}
        resources:
{{ toYaml .Values.browser.resources | indent 10 }}
    {{- end }}
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: WADINFO_BASE_URL
          value: http://{{ .Release.Name }}-wadinfo
        - name: MASTER_BASE_URL
          value: http://{{ .Release.Name }}-master
        - name: IAM_BASE_URL
          value: http://{{ .Release.Name }}-iam
{{ include "dorch.redis-env" . | indent 8 }}
{{ include "dorch.ratelimiter-env" . | indent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-browser
spec:
  selector:
    app: {{ .Release.Name }}-browser
  ports:
    - port: 80
      targetPort: 3000
