{{- $image := printf "%s%s" .Values.registry .Values.master.image -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app: {{ .Release.Name }}-master
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-master
rules:
- apiGroups: ["dorch.beebs.dev"]
  resources: ["games"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-master
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-master
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-master
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-master
spec:
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-master
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-master
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: master
        imagePullPolicy: {{ .Values.master.imagePullPolicy }}
        image: {{ $image }}
    {{- if .Values.master.resources }}
        resources:
{{ toYaml .Values.master.resources | indent 10 }}
    {{- end }}
        command:
          - dorch-master
          - server
          - --internal-port
          - "80"
          - --public-port
          - "3000"
        ports:
        - containerPort: 80
          protocol: TCP
          name: internal
        - containerPort: 3000
          protocol: TCP
          name: public
{{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          protocol: TCP
          name: metrics
{{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
        env:
        - name: SERVICE_NAME
          value: master
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RUST_LOG
          value: info,aws_smithy_runtime=debug,aws_smithy_http_tower=debug,hyper=info
        - name: LOG_LEVEL
          value: {{ .Values.master.logLevel }}
{{ include "dorch.keycloak-env" . | indent 8 }}
{{ include "dorch.metrics-env" . | indent 8 }}
{{ include "dorch.nats-env" . | indent 8 }}
{{ include "dorch.redis-env" . | indent 8 }}
---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-master
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-master
  podMetricsEndpoints:
  - port: metrics
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app: {{ .Release.Name }}-master
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-master
  ports:
  - name: internal
    port: 80
  - name: public
    port: 3000
