{{- $image := printf "%s%s" .Values.registry .Values.sock.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sock
spec:
  replicas: {{ .Values.sock.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sock
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-sock
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: sock
        imagePullPolicy: {{ .Values.sock.imagePullPolicy }}
        image: {{ $image }}
    {{- if .Values.sock.resources }}
        resources:
{{ toYaml .Values.sock.resources | indent 10 }}
    {{- end }}
        command:
          - dorch-sock
          - --port
          - "3000"
        ports:
        - containerPort: 3000
          protocol: TCP
          name: public
{{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          protocol: TCP
          name: metrics
{{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        env:
        - name: SERVICE_NAME
          value: sock
        - name: RUST_LOG
          value: info,aws_smithy_runtime=debug,aws_smithy_http_tower=debug,hyper=info
        - name: LOG_LEVEL
          value: {{ .Values.sock.logLevel }}
{{ include "dorch.nats-env" . | indent 8 }}
{{ include "dorch.redis-env" . | indent 8 }}
{{ include "dorch.keycloak-env" . | indent 8 }}
{{ include "dorch.metrics-env" . | indent 8 }}
---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-sock
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-sock
  podMetricsEndpoints:
  - port: metrics
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sock
  labels:
    app: {{ .Release.Name }}-sock
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-sock
  ports:
  - name: public
    port: 3000
