{{- $image := printf "%s%s" .Values.registry .Values.wadinfo.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wadinfo
spec:
  replicas: {{ .Values.wadinfo.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wadinfo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wadinfo
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: wadinfo
        imagePullPolicy: {{ .Values.wadinfo.imagePullPolicy }}
        image: {{ $image }}
    {{- if .Values.wadinfo.resources }}
        resources:
{{ toYaml .Values.wadinfo.resources | indent 10 }}
    {{- end }}
        command:
          - dorch-wadinfo
          - server
          - --internal-port
          - "80"
          - --public-port
          - "3000"
        ports:
        - containerPort: 80
          protocol: TCP
          name: internal
        - containerPort: 3000
          protocol: TCP
          name: public
{{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          protocol: TCP
          name: metrics
{{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
        env:
        - name: SERVICE_NAME
          value: wadinfo
        - name: RUST_LOG
          value: info,aws_smithy_runtime=debug,aws_smithy_http_tower=debug,hyper=info
        - name: LOG_LEVEL
          value: {{ .Values.wadinfo.logLevel }}
{{ include "dorch.keycloak-env" . | indent 8 }}
{{ include "dorch.metrics-env" . | indent 8 }}
{{ include "dorch.postgres-env" . | indent 8 }}
---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-wadinfo
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wadinfo
  podMetricsEndpoints:
  - port: metrics
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wadinfo
  labels:
    app: {{ .Release.Name }}-wadinfo
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-wadinfo
  ports:
  - name: internal
    port: 80
  - name: public
    port: 3000
