{{- $image := printf "%s%s" .Values.registry .Values.webrtcAuth.image -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webrtc-auth
spec:
  replicas: {{ .Values.webrtcAuth.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webrtc-auth
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-webrtc-auth
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 10 }}
    {{- end }}
      containers:
      - name: webrtc-auth
        imagePullPolicy: {{ .Values.webrtcAuth.imagePullPolicy }}
        image: {{ $image }}
    {{- if .Values.webrtcAuth.resources }}
        resources:
{{ toYaml .Values.webrtcAuth.resources | indent 10 }}
    {{- end }}
        command:
          - dorch-webrtc-auth
          - server
          - --port
          - "80"
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
{{- if .Values.prometheus.enabled }}
        - containerPort: 2112
          protocol: TCP
          name: metrics
{{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
        env:
        - name: SERVICE_NAME
          value: webrtc-auth
        - name: RUST_LOG
          value: info,aws_smithy_runtime=debug,aws_smithy_http_tower=debug,hyper=info
        - name: LOG_LEVEL
          value: {{ .Values.webrtcAuth.logLevel }}
        - name: EXTERNAL_LIVEKIT_URL
          value: {{ .Values.livekit.externalUrl }}
        - name: API_KEY
{{ tpl (toYaml .Values.webrtcAuth.apiKey) . | indent 10 }}
        - name: API_SECRET
{{ tpl (toYaml .Values.webrtcAuth.apiSecret) . | indent 10 }}
{{ include "dorch.keycloak-env" . | indent 8 }}
{{ include "dorch.metrics-env" . | indent 8 }}
---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-webrtc-auth
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webrtc-auth
  podMetricsEndpoints:
  - port: metrics
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webrtc-auth
  labels:
    app: {{ .Release.Name }}-webrtc-auth
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-webrtc-auth
  ports:
  - name: http
    port: 80